### ISSUE TITLE
SSL Certificate expired on translate.erpnext.com

### ISSUE THREAD

**Issue by torstenlemke** [frappe/translator#214]
### Route
```
translation-tool
```
### Trackeback
```
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "env/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "env/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=de&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7fcab9861e10%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1589, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/translate.py", line 1225, in get_messages
    translated_dict = translator.post_api(
  File "apps/frappe/frappe/frappeclient.py", line 341, in post_api
    res = self.session.post(
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "env/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "env/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=de&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7fcab9861e10%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"language": "de"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.translate.get_messages"
}
```
### Response Data
```
{
	"exception": "requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=de&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7fcab9861e10%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))"
}
```

### Module

other

### App Versions
```
{
	"erpnext": "14.0.0-dev",
	"erpnext_germany": "0.0.4",
	"frappe": "15.0.0-dev",
	"frappedesk": "0.5.15",
	"hrms": "1.0.0",
	"payments": "0.0.1"
}
```

### Installation method

None

**Comment by guinanlin** [comment]
+1

**Comment by cgallay** [comment]
I am having the same issue here. Is there another way than the translation tool I could use to translate the name of an DocType attribute?

**Comment by torstenlemke** [comment]
seems to be fixed..
